### ISSUE TITLE
about condition in diffusion process

### ISSUE THREAD

**Issue by 2hiTee** [Zongliang-Wu/LADE-DUN#4]
Thanks for your excellent work! I have a question that in the diffusion process, do you use the condition c via cross attention or concatenate condition with z_t?

**Comment by Zongliang-Wu** [comment]
It uses concatenation operations refer to the code in `train_code_syn/architecture/ddpm_denoising_simple_arch.py`.

**Comment by 2hiTee** [comment]
> It uses concatenation operations refer to the code in `train_code_syn/architecture/ddpm_denoising_simple_arch.py`.

Thanks for your reply! I have found it in the code. Thanks for your wonderful work!
